spring:
    mvc.message-codes-resolver.format: PREFIX_ERROR_CODE
    thymeleaf.prefix: classpath:/templates/
    thymeleaf.cache: false

logging:
    file: logfile.txt   

logging.level:
    org.springframework: INFO
    org.hibernate: ERROR    
    

server:
    port: 8090
    
    
---
 
 spring:
    profiles: localmysql
    
 datasource:
     url: jdbc:mysql://localhost:3306/test?user=root
     username: root
     password: root
     driverClassName: com.mysql.jdbc.Driver
     
---
 
 spring:
    profiles: localpostgres
    
    jpa:
    database: POSTGRESQL
    
    datasource:
     url: jdbc:postgresql://localhost:5432/postgres
     username: postgres
     password: acid
     driverClassName: org.postgresql.Driver
 
    